<?xml version="1.0" encoding="UTF-8"?>
<!--
   Copyright (c) 2010, 2018 The Eclipse Foundation and others.
   All rights reserved. This program and the accompanying materials
   are made available under the terms of the Eclipse Public License v2.0
   which accompanies this distribution, and is available at
   https://www.eclipse.org/legal/epl-2.0/

   SPDX-License-Identifier: EPL-2.0

   Contributors:
   The Eclipse Foundation - initial API and implementation
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.eclipse.epp.mpc</groupId>
		<artifactId>org.eclipse.epp.mpc-parent</artifactId>
		<version>1.14.0-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>
	<artifactId>org.eclipse.epp.mpc.site</artifactId>
	<packaging>eclipse-repository</packaging>
	<name>EPP Marketplace Client</name>

	<properties>
		<org.eclipse.storage.user>genie.mpc</org.eclipse.storage.user>
		<org.eclipse.justj.p2.manager.remote>${org.eclipse.storage.user}@projects-storage.eclipse.org:/home/data/httpd/download.eclipse.org/technology/mpc</org.eclipse.justj.p2.manager.remote>
		<org.eclipse.justj.p2.manager.relative>updates</org.eclipse.justj.p2.manager.relative>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<org.eclipse.justj.p2.manager.build.url>http://www.example.com/</org.eclipse.justj.p2.manager.build.url>
		<build.type>nightly</build.type>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-p2-repository-plugin</artifactId>
				<configuration>
					<includeAllDependencies>false</includeAllDependencies>
					<includeAllSources>true</includeAllSources>
					<compress>false</compress>
					<xzCompress>false</xzCompress>
					<skipArchive>true</skipArchive>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>promote</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.eclipse.tycho.extras</groupId>
						<artifactId>tycho-p2-extras-plugin</artifactId>
						<version>${tycho-version}</version>
						<executions>
							<execution>
								<id>promote-build</id>
								<phase>post-integration-test</phase>
								<goals>
									<goal>p2-manager</goal>
								</goals>
								<configuration>
									<retain>5</retain>
									<label>Marketplace Client</label>
									<buildUrl>${org.eclipse.justj.p2.manager.build.url}</buildUrl>
									<remote>${org.eclipse.justj.p2.manager.remote}</remote>
									<root>${project.basedir}/mpc</root>
									<relative>${org.eclipse.justj.p2.manager.relative}</relative>
									<versionIU>org.eclipse.epp.mpc.feature.group</versionIU>
									<iuFilterPattern>org.eclipse.epp.mpc.(core|feature|help|ui).*</iuFilterPattern>
									<excludedCategoriesPattern>.*no.category</excludedCategoriesPattern>
									<commit>https://github.com/eclipse-mpc/epp.mpc/commit/${git.commit}</commit>
									<targetUrl>https://download.eclipse.org/mpc</targetUrl>
									<promote>${project.basedir}/target/repository</promote>
									<timestamp>${build.timestamp}</timestamp>
									<type>${build.type}</type>
									<breadcrumbs>
										<breadcrumb>Marketplace&#xA0;Client https://projects.eclipse.org/projects/technology.packaging.mpc</breadcrumb>
									</breadcrumbs>
									<mappings>
										<mapping> mpc->Marketplace&#xA0;Client</mapping>
									</mappings>
									<favicon>https://raw.githubusercontent.com/eclipse-mpc/epp.mpc/master/org.eclipse.epp.mpc.ui/icons/svg/marketplace32.svg</favicon>
									<bodyImage>https://raw.githubusercontent.com/eclipse-mpc/epp.mpc/master/org.eclipse.epp.mpc.ui/icons/svg/marketplace32.svg</bodyImage>
									<titleImage>https://www.eclipse.org/eclipse.org-common/themes/solstice/public/images/marketplace/logo.png</titleImage>
									<bree>true</bree>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
